export const defaultColleges = [
  {
    id: "kjk1",
    name: "Abdul Ahad Azad Memorial Degree College, Bemina",
    lat: 34.0740,
    lon: 74.8160,
    address: "Bemina, Srinagar, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "60%",
    medium: "English/Urdu",
    facilities: "Library, Labs, Hostel, Internet"
  },
  {
    id: "kjk2",
    name: "Amar Singh College, Gogji Bagh",
    lat: 34.0905,
    lon: 74.8188,
    address: "Gogji Bagh, Srinagar, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "60%",
    medium: "English/Urdu",
    facilities: "Library, Labs, Hostel, Internet"
  },
  {
    id: "kjk3",
    name: "Gandhi Memorial College, Shamaswari",
    lat: 34.0745,
    lon: 74.8090,
    address: "Shamaswari, Srinagar, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "55%",
    medium: "English/Urdu",
    facilities: "Library, Labs, Internet"
  },
  {
    id: "kjk4",
    name: "Government College for Women, M.A. Road",
    lat: 34.0750,
    lon: 74.8100,
    address: "M.A. Road, Srinagar, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "55%",
    medium: "English/Urdu",
    facilities: "Library, Labs, Hostel, Internet"
  },
  {
    id: "kjk5",
    name: "Government Degree College, Chadoora",
    lat: 34.0472,
    lon: 75.2030,
    address: "Chadoora, Budgam, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs, Internet"
  },
  {
    id: "kjk6",
    name: "Government Degree College, Beerwah",
    lat: 34.0383,
    lon: 75.2085,
    address: "Beerwah, Budgam, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk7",
    name: "Government Degree College, Charar-i-Sharief",
    lat: 34.0755,
    lon: 75.1592,
    address: "Charar-i-Sharief, Budgam, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk8",
    name: "Government Degree College, Khansahib",
    lat: 34.0567,
    lon: 75.1264,
    address: "Khansahib, Budgam, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk9",
    name: "Government Degree College, Magam",
    lat: 34.1055,
    lon: 75.1231,
    address: "Magam, Budgam, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk10",
    name: "Government Degree College, Soibugh",
    lat: 34.0802,
    lon: 74.8156,
    address: "Soibugh, Budgam, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk11",
    name: "Government Degree College, Waterhail",
    lat: 34.0850,
    lon: 74.8200,
    address: "Waterhail, Budgam, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library"
  },
  {
    id: "kjk12",
    name: "Government Degree College, Anantnag",
    lat: 33.7319,
    lon: 75.1520,
    address: "Anantnag, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "55%",
    medium: "English/Urdu",
    facilities: "Library, Labs, Hostel, Internet"
  },
  {
    id: "kjk13",
    name: "Government Degree College, Bijbehara",
    lat: 33.8684,
    lon: 75.0730,
    address: "Bijbehara, Anantnag, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "55%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk14",
    name: "Government Degree College, Doru",
    lat: 33.8700,
    lon: 75.1430,
    address: "Doru, Anantnag, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk15",
    name: "Government Degree College, Ganderbal",
    lat: 34.2289,
    lon: 75.3658,
    address: "Ganderbal, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs, Internet"
  },
  {
    id: "kjk16",
    name: "Government Degree College, Kangan",
    lat: 34.2560,
    lon: 75.3670,
    address: "Kangan, Ganderbal, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs, Internet"
  },
  {
    id: "kjk17",
    name: "Government Degree College, Pattan",
    lat: 34.2000,
    lon: 74.6250,
    address: "Pattan, Baramulla, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "55%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk18",
    name: "Government Degree College, Sopore",
    lat: 34.2935,
    lon: 74.4670,
    address: "Sopore, Baramulla, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "55%",
    medium: "English/Urdu",
    facilities: "Library, Labs, Internet"
  },
  {
    id: "kjk19",
    name: "Government Degree College, Bandipora",
    lat: 34.4170,
    lon: 74.6400,
    address: "Bandipora, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk20",
    name: "Government Degree College, Baramulla",
    lat: 34.1990,
    lon: 74.3630,
    address: "Baramulla, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "55%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk21",
    name: "Government Degree College, Pulwama",
    lat: 33.8731,
    lon: 74.8935,
    address: "Pulwama, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "55%",
    medium: "English/Urdu",
    facilities: "Library, Labs, Hostel"
  },
  {
    id: "kjk22",
    name: "Government Degree College, Shopian",
    lat: 33.7090,
    lon: 74.8110,
    address: "Shopian, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk23",
    name: "Government Degree College, Kulgam",
    lat: 33.6380,
    lon: 75.0200,
    address: "Kulgam, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs, Hostel"
  },
  {
    id: "kjk24",
    name: "Government Degree College, Tral",
    lat: 33.9130,
    lon: 75.0750,
    address: "Tral, Pulwama, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk25",
    name: "Government Degree College, Pampore",
    lat: 33.8720,
    lon: 75.0920,
    address: "Pampore, Pulwama, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk26",
    name: "Government Degree College, Awantipora",
    lat: 33.8580,
    lon: 75.1000,
    address: "Awantipora, Pulwama, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk27",
    name: "Government Degree College, Khrew",
    lat: 33.8570,
    lon: 75.1060,
    address: "Khrew, Pulwama, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk28",
    name: "Government Degree College, Pahalgam",
    lat: 33.7150,
    lon: 75.1830,
    address: "Pahalgam, Anantnag, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk29",
    name: "Government Degree College, Qazigund",
    lat: 33.7180,
    lon: 75.0570,
    address: "Qazigund, Anantnag, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk30",
    name: "Government Degree College for Women, Anantnag",
    lat: 33.7290,
    lon: 75.1550,
    address: "Anantnag, J&K",
    programs: "B.A, B.Sc",
    eligibility: "12th Pass",
    cut_off: "55%",
    medium: "English/Urdu",
    facilities: "Library, Labs, Hostel"
  },
  {
    id: "kjk31",
    name: "Government Degree College, Sopore Women",
    lat: 34.2920,
    lon: 74.4680,
    address: "Sopore, Baramulla, J&K",
    programs: "B.A, B.Sc",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk32",
    name: "Government Degree College, Bandipora Women",
    lat: 34.4180,
    lon: 74.6410,
    address: "Bandipora, J&K",
    programs: "B.A, B.Sc",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Labs"
  },
  {
    id: "kjk33",
    name: "Government Degree College, Baramulla Women",
    lat: 34.2000,
    lon: 74.3640,
    address: "Baramulla, J&K",
    programs: "B.A, B.Sc",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library"
  },
  {
    id: "kjk34",
    name: "Government Degree College, Pulwama Women",
    lat: 33.8740,
    lon: 74.8940,
    address: "Pulwama, J&K",
    programs: "B.A, B.Sc",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Hostel"
  },
  {
    id: "kjk35",
    name: "Government Degree College, Shopian Women",
    lat: 33.7100,
    lon: 74.8120,
    address: "Shopian, J&K",
    programs: "B.A, B.Sc",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library"
  },
  {
    id: "kjk36",
    name: "Government Degree College, Kulgam Women",
    lat: 33.6390,
    lon: 75.0210,
    address: "Kulgam, J&K",
    programs: "B.A, B.Sc",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library, Hostel"
  },
  {
    id: "kjk37",
    name: "Government Degree College, Tral Women",
    lat: 33.9140,
    lon: 75.0760,
    address: "Tral, Pulwama, J&K",
    programs: "B.A, B.Sc",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library"
  },
  {
    id: "kjk38",
    name: "Government Degree College, Pampore Women",
    lat: 33.8730,
    lon: 75.0930,
    address: "Pampore, Pulwama, J&K",
    programs: "B.A, B.Sc",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library"
  },
  {
    id: "kjk39",
    name: "Government Degree College, Awantipora Women",
    lat: 33.8590,
    lon: 75.1010,
    address: "Awantipora, Pulwama, J&K",
    programs: "B.A, B.Sc",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library"
  },
  {
    id: "kjk40",
    name: "Government Degree College, Khrew Women",
    lat: 33.8580,
    lon: 75.1070,
    address: "Khrew, Pulwama, J&K",
    programs: "B.A, B.Sc",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library"
  },
  {
    id: "kjk41",
    name: "Government Degree College, Pahalgam Women",
    lat: 33.7160,
    lon: 75.1840,
    address: "Pahalgam, Anantnag, J&K",
    programs: "B.A, B.Sc",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library"
  },
  {
    id: "kjk42",
    name: "Government Degree College, Qazigund Women",
    lat: 33.7190,
    lon: 75.0580,
    address: "Qazigund, Anantnag, J&K",
    programs: "B.A, B.Sc",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Urdu",
    facilities: "Library"
  },
  {
    id: "jjk43",
    name: "Government Degree College, Paloura",
    lat: 32.7110,
    lon: 74.8570,
    address: "Paloura, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "55%",
    medium: "English/Hindi",
    facilities: "Library, Labs"
  },
  {
    id: "jjk44",
    name: "Government Degree College, Kunjwani",
    lat: 32.7210,
    lon: 74.8575,
    address: "Kunjwani, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "55%",
    medium: "English/Hindi",
    facilities: "Library, Labs"
  },
  {
    id: "jjk45",
    name: "Government Degree College, Akhnoor",
    lat: 32.8310,
    lon: 74.4700,
    address: "Akhnoor, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library, Labs"
  },
  {
    id: "jjk46",
    name: "Government Degree College, Bishnah",
    lat: 32.6900,
    lon: 74.8100,
    address: "Bishnah, Jammu, J&K",
    programs: "B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk47",
    name: "Government Degree College, Billawar",
    lat: 32.7000,
    lon: 75.2000,
    address: "Billawar, Kathua, J&K",
    programs: "B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk48",
    name: "Government Degree College, Basohli",
    lat: 32.4000,
    lon: 75.4800,
    address: "Basohli, Kathua, J&K",
    programs: "B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk49",
    name: "Government Degree College, Doda",
    lat: 33.1300,
    lon: 75.4300,
    address: "Doda, J&K",
    programs: "B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk50",
    name: "Government Degree College, Bhaderwah",
    lat: 33.0200,
    lon: 75.7800,
    address: "Bhaderwah, Doda, J&K",
    programs: "B.Com, PG in Chemistry, PG in Urdu, PG in Persian",
    eligibility: "12th Pass",
    cut_off: "55%",
    medium: "English/Hindi",
    facilities: "Library, Labs, Hostel"
  },
  {
    id: "jjk51",
    name: "Government Degree College, Rajouri",
    lat: 33.3830,
    lon: 74.2910,
    address: "Rajouri, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk52",
    name: "Government Degree College, Poonch",
    lat: 33.7700,
    lon: 74.0900,
    address: "Poonch, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk53",
    name: "Government Degree College, Kathua",
    lat: 32.3700,
    lon: 75.5300,
    address: "Kathua, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk54",
    name: "Government Degree College, Udhampur (Boys)",
    lat: 32.9300,
    lon: 75.1200,
    address: "Udhampur, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk55",
    name: "Government Degree College, Udhampur (Women)",
    lat: 32.9350,
    lon: 75.1250,
    address: "Udhampur, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk56",
    name: "Government Degree College, Reasi",
    lat: 33.0500,
    lon: 74.8300,
    address: "Reasi, Jammu, J&K",
    programs: "B.A",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk57",
    name: "Government Degree College, Ramnagar",
    lat: 32.9210,
    lon: 75.0840,
    address: "Ramnagar, Udhampur, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk58",
    name: "Government Degree College, Samba",
    lat: 32.5300,
    lon: 75.1000,
    address: "Samba, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk59",
    name: "Government Degree College, Reasi Women",
    lat: 33.0520,
    lon: 74.8320,
    address: "Reasi, Jammu, J&K",
    programs: "B.A",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk60",
    name: "Government Degree College, Samba Women",
    lat: 32.5320,
    lon: 75.1020,
    address: "Samba, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk61",
    name: "Government Degree College, Kathua Women",
    lat: 32.3720,
    lon: 75.5320,
    address: "Kathua, Jammu, J&K",
    programs: "B.A, B.Sc",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk62",
    name: "Government Degree College, Billawar Women",
    lat: 32.7020,
    lon: 75.2020,
    address: "Billawar, Kathua, J&K",
    programs: "B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk63",
    name: "Government Degree College, Basohli Women",
    lat: 32.4020,
    lon: 75.4820,
    address: "Basohli, Kathua, J&K",
    programs: "B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk64",
    name: "Government Degree College, Doda Women",
    lat: 33.1320,
    lon: 75.4320,
    address: "Doda, J&K",
    programs: "B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk65",
    name: "Government Degree College, Bhaderwah Women",
    lat: 33.0220,
    lon: 75.7820,
    address: "Bhaderwah, Doda, J&K",
    programs: "B.Com, PG in Chemistry, PG in Urdu, PG in Persian",
    eligibility: "12th Pass",
    cut_off: "55%",
    medium: "English/Hindi",
    facilities: "Library, Labs, Hostel"
  },
  {
    id: "jjk66",
    name: "Government Degree College, Rajouri Women",
    lat: 33.3840,
    lon: 74.2920,
    address: "Rajouri, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk67",
    name: "Government Degree College, Poonch Women",
    lat: 33.7720,
    lon: 74.0920,
    address: "Poonch, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk68",
    name: "Government Degree College, Udhampur Women",
    lat: 32.9360,
    lon: 75.1260,
    address: "Udhampur, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk69",
    name: "Government Degree College, Reasi Women",
    lat: 33.0530,
    lon: 74.8330,
    address: "Reasi, Jammu, J&K",
    programs: "B.A",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk70",
    name: "Government Degree College, Ramnagar Women",
    lat: 32.9220,
    lon: 75.0850,
    address: "Ramnagar, Udhampur, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk71",
    name: "Government Degree College, Samba Women",
    lat: 32.5340,
    lon: 75.1030,
    address: "Samba, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk72",
    name: "Government College for Women, Jammu University Campus",
    lat: 32.7340,
    lon: 74.8570,
    address: "University Campus, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "55%",
    medium: "English/Hindi",
    facilities: "Library, Labs, Hostel, Internet"
  },
  {
    id: "jjk73",
    name: "Government College, Akhnoor Men",
    lat: 32.8320,
    lon: 74.4710,
    address: "Akhnoor, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library, Labs"
  },
  {
    id: "jjk74",
    name: "Government College, Kathua Men",
    lat: 32.3730,
    lon: 75.5330,
    address: "Kathua, Jammu, J&K",
    programs: "B.A, B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  },
  {
    id: "jjk75",
    name: "Government College, Billawar Men",
    lat: 32.7030,
    lon: 75.2030,
    address: "Billawar, Kathua, J&K",
    programs: "B.Sc, B.Com",
    eligibility: "12th Pass",
    cut_off: "50%",
    medium: "English/Hindi",
    facilities: "Library"
  }
];